# Generated by Django 5.1.15 on 2026-08-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, help_text='Public slug used in booking links, e.g. /public/<username>/<slug>/.', null=True, unique=True, verbose_name='public username'),
        ),
    ]
