# Generated by Django 5.1.15 on 2026-08-16 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Public slug used in booking links, e.g. /public/<user>/<slug>/.', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Meeting length in minutes.')),
                ('buffer_before', models.PositiveIntegerField(default=0, help_text='Minutes kept free before a meeting.')),
                ('buffer_after', models.PositiveIntegerField(default=0, help_text='Minutes kept free after a meeting.')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_name', models.CharField(max_length=255)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('meet_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('cancellation_token', models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='meetings.eventtype')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='meetings.eventtype')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='uniq_event_type_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gt', 0)), name='event_type_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_before__gte', 0)), name='event_type_buffer_before_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_after__gte', 0)), name='event_type_buffer_after_non_negative'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event_type', 'start_time'], name='meetings_bo_event_t_2f915f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_time'], name='meetings_bo_status_1c6efa_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('event_type', 'start_time'), name='uniq_booking_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='availability_weekday_in_range'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
    ]
